"""autogenerated by genpy from graph_slam/Edge.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import graph_slam.msg

class Edge(genpy.Message):
  _md5sum = "725b40920ff64ae7ec6c42f719a033e1"
  _type = "graph_slam/Edge"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#delta is in the frame of node "from"
#Node delta
Node delta
uint16 from
uint16 to
float64[9] covariance

================================================================================
MSG: graph_slam/Node
float64 x
float64 y
float64 theta


"""
  __slots__ = ['delta','from_','to','covariance']
  _slot_types = ['graph_slam/Node','uint16','uint16','float64[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       delta,from_,to,covariance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Edge, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.delta is None:
        self.delta = graph_slam.msg.Node()
      if self.from_ is None:
        self.from_ = 0
      if self.to is None:
        self.to = 0
      if self.covariance is None:
        self.covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
    else:
      self.delta = graph_slam.msg.Node()
      self.from_ = 0
      self.to = 0
      self.covariance = [0.,0.,0.,0.,0.,0.,0.,0.,0.]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d2H.pack(_x.delta.x, _x.delta.y, _x.delta.theta, _x.from_, _x.to))
      buff.write(_struct_9d.pack(*self.covariance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.delta is None:
        self.delta = graph_slam.msg.Node()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.delta.x, _x.delta.y, _x.delta.theta, _x.from_, _x.to,) = _struct_3d2H.unpack(str[start:end])
      start = end
      end += 72
      self.covariance = _struct_9d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d2H.pack(_x.delta.x, _x.delta.y, _x.delta.theta, _x.from_, _x.to))
      buff.write(self.covariance.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.delta is None:
        self.delta = graph_slam.msg.Node()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.delta.x, _x.delta.y, _x.delta.theta, _x.from_, _x.to,) = _struct_3d2H.unpack(str[start:end])
      start = end
      end += 72
      self.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d2H = struct.Struct("<3d2H")
_struct_9d = struct.Struct("<9d")
